language: node_js
node_js:
  - 8.6.0  # latest
  - 6.11.4 # lts

script:
  - set -e
  - cd lib
  - rm -rfv commands.json
  - git clone https://github.com/qutebrowser/qutebrowser.git
  - chmod +x generate-commands.sh && ./generate-commands.sh
  - docker run -it --rm -v "$PWD:$PWD" -w "$PWD" koalaman/shellcheck:v0.4.6 shellcheck generate-commands.sh
  - cd ../
  - yarn
  - yarn test
