language: node_js
node_js:
  - 9.3.0  # latest
  - 8.9.4 # lts

script:
  - set -e
  - cd lib
  - rm -rfv commands.json
  - git clone https://github.com/qutebrowser/qutebrowser.git
  - chmod +x generate-commands.sh && ./generate-commands.sh
  - docker run -it --rm -v "$PWD:$PWD" -w "$PWD" base/archlinux sh -c  "set -e;pacman -Syu --noconfirm &> /dev/null;pacman -S shellcheck --noconfirm &> /dev/null;shellcheck generate-commands.sh"
  - cd ../
  - yarn
  - yarn test
